import { useState } from 'react';
import { Map, Users, MessageSquare, Lightbulb, Target, Copy, Check, Download } from 'lucide-react';

export interface BriefData {
  landscapeSummary: string;
  whoIsPlaying: string[];
  dominantMessagingThemes: string[];
  theGap: string;
  recommendedAngle: string;
}

function SectionHeader({ icon: Icon, title, accent }: { icon: React.ElementType; title: string; accent?: boolean }) {
  return (
    <div className={`flex items-center gap-2.5 mb-3 ${accent ? 'text-amber-400' : 'text-gray-300'}`}>
      <div className={`w-8 h-8 rounded-lg flex items-center justify-center ${accent ? 'bg-amber-900/50' : 'bg-gray-700/60'}`}>
        <Icon className="w-4 h-4" />
      </div>
      <h3 className="text-sm font-bold uppercase tracking-wide">{title}</h3>
    </div>
  );
}

function briefToPlainText(data: BriefData): string {
  return [
    'COMPETITIVE BRIEF',
    '=================',
    '',
    'LANDSCAPE SUMMARY',
    data.landscapeSummary,
    '',
    'WHO IS PLAYING',
    data.whoIsPlaying.join(', '),
    '',
    'DOMINANT MESSAGING THEMES',
    ...data.dominantMessagingThemes.map((t) => `• ${t}`),
    '',
    'THE GAP',
    data.theGap,
    '',
    'YOUR RECOMMENDED ANGLE',
    data.recommendedAngle,
  ].join('\n');
}

export default function BriefResultsCard({ data }: { data: BriefData }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(briefToPlainText(data));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadPdf = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Competitive Brief — ScoutAI</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 48px; color: #1a1a1a; line-height: 1.6; max-width: 800px; margin: 0 auto; }
          h1 { font-size: 22px; margin-bottom: 6px; }
          .subtitle { color: #6b7280; font-size: 13px; margin-bottom: 36px; }
          h2 { font-size: 13px; text-transform: uppercase; letter-spacing: 0.05em; font-weight: 700; color: #374151; margin-bottom: 10px; margin-top: 28px; }
          p { font-size: 14px; color: #374151; margin-bottom: 8px; }
          .players { display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 8px; }
          .player-tag { background: #f1f5f9; border: 1px solid #e2e8f0; border-radius: 6px; padding: 4px 10px; font-size: 13px; color: #334155; }
          ul { padding-left: 20px; margin-bottom: 8px; }
          li { font-size: 14px; color: #374151; margin-bottom: 6px; }
          .gap-box { background: #fffbeb; border: 2px solid #fbbf24; border-radius: 10px; padding: 16px 20px; margin-top: 8px; }
          .gap-box p { color: #78350f; font-weight: 500; }
          .angle-box { background: #f0fdfa; border: 1px solid #99f6e4; border-radius: 10px; padding: 16px 20px; margin-top: 8px; }
          .angle-box p { color: #134e4a; }
          @media print { body { padding: 24px; } }
        </style>
      </head>
      <body>
        <h1>Competitive Brief</h1>
        <p class="subtitle">Generated by ScoutAI</p>

        <h2>Landscape Summary</h2>
        <p>${data.landscapeSummary}</p>

        <h2>Who Is Playing</h2>
        <div class="players">
          ${data.whoIsPlaying.map((p) => `<span class="player-tag">${p}</span>`).join('')}
        </div>

        <h2>Dominant Messaging Themes</h2>
        <ul>
          ${data.dominantMessagingThemes.map((t) => `<li>${t}</li>`).join('')}
        </ul>

        <h2>The Gap</h2>
        <div class="gap-box"><p>${data.theGap}</p></div>

        <h2>Your Recommended Angle</h2>
        <div class="angle-box"><p>${data.recommendedAngle}</p></div>
      </body>
      </html>
    `;

    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.onload = () => {
      printWindow.print();
    };
  };

  return (
    <div className="w-full max-w-3xl mx-auto animate-fade-in">
      <div className="bg-gray-800/60 backdrop-blur-md rounded-2xl shadow-2xl shadow-black/40 border border-gray-700/50 overflow-hidden">
        {/* Card header */}
        <div className="px-8 py-5 border-b border-gray-700/50 bg-gray-800/50 flex items-center justify-between">
          <div>
            <h2 className="text-lg font-bold text-gray-100">Competitive Brief</h2>
            <p className="text-sm text-gray-400 mt-0.5">Generated by ScoutAI</p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className={`inline-flex items-center gap-1.5 px-3.5 py-2 rounded-lg text-sm font-medium transition-all duration-200 ${
                copied
                  ? 'bg-amber-900/50 text-amber-300 border border-amber-600/50'
                  : 'bg-gray-700 text-gray-300 border border-gray-600 hover:bg-gray-600 hover:border-gray-500'
              }`}
            >
              {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? 'Copied' : 'Copy'}
            </button>
            <button
              onClick={handleDownloadPdf}
              className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-lg text-sm font-medium bg-gray-700 text-gray-300 border border-gray-600 hover:bg-gray-600 hover:border-gray-500 transition-all duration-200"
            >
              <Download className="w-3.5 h-3.5" />
              PDF
            </button>
          </div>
        </div>

        <div className="p-8 space-y-8">
          {/* 1. Landscape Summary */}
          <section>
            <SectionHeader icon={Map} title="Landscape Summary" />
            <p className="text-gray-300 leading-relaxed text-[15px] pl-10">
              {data.landscapeSummary}
            </p>
          </section>

          {/* 2. Who Is Playing */}
          <section>
            <SectionHeader icon={Users} title="Who Is Playing" />
            <div className="pl-10 flex flex-wrap gap-2">
              {data.whoIsPlaying.map((player) => (
                <span
                  key={player}
                  className="inline-flex items-center px-3 py-1.5 rounded-lg bg-gray-700/60 text-gray-200 text-sm font-medium border border-gray-600/60"
                >
                  {player}
                </span>
              ))}
            </div>
          </section>

          {/* 3. Dominant Messaging Themes */}
          <section>
            <SectionHeader icon={MessageSquare} title="Dominant Messaging Themes" />
            <ul className="pl-10 space-y-2">
              {data.dominantMessagingThemes.map((theme) => (
                <li key={theme} className="flex items-start gap-2.5 text-[15px] text-gray-300">
                  <span className="mt-2 w-1.5 h-1.5 rounded-full bg-amber-400 shrink-0" />
                  <span className="leading-relaxed">{theme}</span>
                </li>
              ))}
            </ul>
          </section>

          {/* 4. The Gap — visually prominent gold callout */}
          <section>
            <SectionHeader icon={Lightbulb} title="The Gap" accent />
            <div className="ml-10 relative rounded-xl border-2 border-amber-600/60 bg-gradient-to-br from-amber-950/50 via-yellow-950/40 to-orange-950/40 p-5 shadow-lg shadow-amber-900/20">
              <div className="absolute top-0 left-0 w-full h-1 rounded-t-xl bg-gradient-to-r from-amber-400 via-yellow-400 to-orange-400" />
              <p className="text-amber-100 leading-relaxed text-[15px] font-medium">
                {data.theGap}
              </p>
            </div>
          </section>

          {/* 5. Your Recommended Angle */}
          <section>
            <SectionHeader icon={Target} title="Your Recommended Angle" />
            <div className="pl-10 p-4 rounded-xl bg-blue-900/25 border border-blue-700/40">
              <p className="text-blue-200 leading-relaxed text-[15px]">
                {data.recommendedAngle}
              </p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
